spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.yourcompany.project.domain
  configuration:
    map-underscore-to-camel-case: true
