spring:
  datasource: 
             url: jdbc:postgresql://localhost:5432/springfirst
             username: postgres
             password: 0932
             driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: co.study.firstSpring.domain
  configuration:
    map-underscore-to-camel-case: true
